apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secscan
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    # Add "127.0.0.1 secscan.local" to your hosts file, then open http://secscan.local
    - host: secscan.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: secscan
                port:
                  number: 80
